config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  resources :coachsessions do
    resources :bookings, only: [:index, :create]
    resources :reviews, only: :create
  end
  resources :bookings, only: [:destroy, :index, :create]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/booking.rb
class Booking < ApplicationRecord
  STATUS = ["Accepted", "pending", "Rejected"]
  belongs_to :user
  belongs_to :coach_session

  validates :total_amount, :date_start, :date_end, presence: true
  has_one_attached :avatar
  validates :status, inclusion: { in: STATUS }
end

app/models/coach_session.rb
class CoachSession < ApplicationRecord
  ACTIVITIES = ['Surfing', 'Weight-Lifting', 'Calisthenics', "Yoga", "Swimming", "Dancing"]
  belongs_to :user
  has_many :reviews, dependent: :destroy
  validates :session_name, :type_of_activity, :price_per_day, presence: true
  validates :price_per_day, numericality: true
  validates :type_of_activity, inclusion: {in: ACTIVITIES}

  has_one_attached :main_photo
  validates :main_photo, presence: true

  geocoded_by :address
  after_validation :geocode, if: :will_save_change_to_address?

  include PgSearch::Model
  pg_search_scope :search_by_type_of_activity,
    against: [ :type_of_activity ],
    using: {
      tsearch: { prefix: true }
    }
end

# CoachSession.create(session_name:"Bench Press Training", type_of_activity:"Weight-Lifting", price_per_day: 30, user_id: 4)

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :coach_session
  validates :content, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  has_many :coach_sessions, dependent: :destroy
  has_many :bookings

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
  def index
    @user = current_user
    @bookings = @user.bookings
  end

  def create
    @booking = Booking.new(booking_params)
    @coachsession = CoachSession.find(params[:coachsession_id])
    @booking.total_amount = (@booking.date_end - @booking.date_start) * @coachsession.price_per_day
    # set the user
    @booking.user = current_user
    # set the session id to the booking
    @booking.coach_session = @coachsession
    if @booking.save
      redirect_to bookings_path
    else
      render 'coachsessions/show'
    end
  end

  def destroy
    @booking = Booking.find(params[:id])
    @booking.destroy
    redirect_to bookings_path
  end

  private

  def booking_params
    params.require(:booking).permit(:date_start, :date_end)
  end
end

app/controllers/coachsessions_controller.rb
class CoachsessionsController < ApplicationController

  def index
    if params[:query]
      @coachsessions = CoachSession.search_by_type_of_activity(params[:query])
    else
      @coachsessions = CoachSession.all
    end

    @markers = @coachsessions.geocoded.map do |coachsession|
      {
        lat: coachsession.latitude,
        lng: coachsession.longitude,
        info_window: render_to_string(partial: "info_window", locals: { coachsession: coachsession })
      }
    end
  end

  def show
    @coachsession = set_coachsession
    @booking = Booking.new
    @review = Review.new
  end

  def create
    @coachsession = CoachSession.new(coachsession_params)
    @coachsession.user = current_user
    if @coachsession.save
      redirect_to coachsessions_path(@coachsession)
    else
      render :new
    end
  end

  def new
    @coachsession = CoachSession.new
  end

  def edit
  end

  def update
  end

  def destroy
    @coachsession = CoachSession.find(params[:id])
    @coachsession.destroy
    redirect_to coachsessions_path(@coachsession)
  end

  private

  def set_coachsession
    CoachSession.find(params[:id])
  end

  def coachsession_params
    params.require(:coach_session).permit(:session_name, :type_of_activity, :description, :price_per_day, :address, :main_photo)
  end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
    @user = current_user
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  def create
    @coachsession = CoachSession.find(params[:coachsession_id])
    @review = Review.new(review_params)
    @review.coach_session = @coachsession
    if @review.save
      redirect_to coachsession_path(@coachsession, anchor: "review-#{@review.id}")
    else
      render 'coachsessions/show'
    end
  end

  private

  def review_params
    params.require(:review).permit(:content)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/bookings/index.html.erb
<h1 id="dashboard-title">Your Bookings</h1>

<div class="booking-client-cards">
  <% @bookings.each do |booking| %>
    <% unless @user.id === booking.coach_session.user_id  %>
      <div class="booking-client-card">
        <img class="booking-client-card-img" src="<%= cl_image_path booking.coach_session.main_photo.key %>">
        <div class="booking-client-card-text">
          <h2><%= booking.coach_session.session_name %></h2>
          <p>From <%= booking.date_start.strftime %></p>
          <p>To <%= booking.date_end.strftime %></p>
        </div>
      </div>
    <% end %>
  <% end %>
</div>

<h1 id="dashboard-title">Your Inviations</h1>

<div class="booking-client-cards">
  <% @user.bookings.each do |booking| %>
    <% if @user.id === booking.coach_session.user_id  %>
      <div class="booking-client-card">
        <img class="booking-client-card-img" src="<%= cl_image_path booking.coach_session.main_photo.key %>">
        <div class="booking-client-card-text">
          <h2><%= booking.coach_session.session_name %></h2>
          <p>From <%= booking.date_start.strftime %></p>
          <p>To <%= booking.date_end.strftime %></p>
        </div>
        <div class="booking-client-status-button">
          <p><%= link_to "ACCEPT", booking_path(booking), class: "btn-booking", method: :delete %></p>
          <p><%= link_to "REJECT", booking_path(booking), class: "btn-booking", method: :delete %></p>
        </div>
      </div>
    <% end %>
  <% end %>
</div>

app/views/coachsessions/_form.html.erb
<div class="container">
<%= simple_form_for @coachsession, url: coachsessions_path do |f| %>
<%= f.input :session_name %>
<%= f.input :type_of_activity, collection: CoachSession::ACTIVITIES %>
<%= f.input :price_per_day %>
<%= f.input :description %>
<%= f.input :address %>
<%= f.input :main_photo, as: :file %>
<button class="btn-booking btn-session">Create the Session</button>
<% end %>
</div>

app/views/coachsessions/_info_window.html.erb
<div class="card-pop-up">
<img class="pop-up-image" src="<%= cl_image_path coachsession.main_photo.key %>">
  <div class="pop-up-text">
    <a href="#"><%= link_to coachsession.session_name, coachsession_path(coachsession) %></a>
    <p><%= coachsession.description %></p>
  </div>
</div>

app/views/coachsessions/index.html.erb
<div class="card-wrapper">
  <div class="cards">
    <% @coachsessions.each do |session| %>
      <%= link_to coachsession_path(session) do %>
        <%if session.main_photo.attached?%>
          <div class="card-category" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url( <%= cl_image_path session.main_photo.key %> )">
            <div>
              <h5 class="card-title"> <%= session.session_name %> </h5>
              <p class="card-text"><%=session.price_per_day%> $</p>
            </div>
          </div>
        <% else %>
          <div style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3), url(<%= image_path "calisthenics_1.jpeg"%>))">
            <div>
              <h5 class="card-title"> <%= session.session_name %> </h5>
              <p class="card-text"><%=session.price_per_day%> $</p>
            </div>
          </div>
        <% end %>
      <% end %>
    <% end %>
  </div>
  <div id="map"
    data-controller="mapbox"
    data-mapbox-markers-value="<%= @markers.to_json %>"
    data-mapbox-api-key-value="<%= ENV['MAPBOX_API_KEY'] %>">
  </div>
</div>

app/views/coachsessions/new.html.erb
<div class="jumbotron jumbotron-fluid mt-5">
  <div class="container col-6">
    <h3 class="display-4" class="p-2 bg-light border">Add New Coach Session</h3>
    <hr class="my-4">
    <%= render 'form' %>
    <br>
    <div class="btn btn-secondary mx-2">
      <%= link_to "Back to Coach Sessions", coachsessions_path, class: "text-white text-decoration-none"%>
    </div>
  </div>
</div>

app/views/coachsessions/show.html.erb
<div>
  <div class="intro">
    <div class="profile-details">
      <div class="card mb-3 d-flex">
        <div class="row g-0">
          <div class="col-md-6">
            <div class="img-fluid rounded-start profile-photo"  style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url( <%= cl_image_path @coachsession.main_photo.key %> )"></div>
          </div>
          <div class="col-md-6">
            <div class="card-body">
              <h1 class="card-title"><%= @coachsession.session_name %></h1>
              <h5 class="card-description"><%=@coachsession.description%></h5>
              <p class="card-location"><i class="fas fa-map-marker-alt"></i>  <%=@coachsession.address%></p>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>
<div class="row pb-10 profile-details">
  <div class="col-md-8">
    <div class="card-body" id="reviews">
      <p class="review"><%= pluralize @coachsession.reviews.size, "review" %></p>
      <% if @coachsession.reviews.blank? %>
        <p class="review">Help the coach to spread his experience.
        Leave the first review for the session!</p>
      <% else %>
        <% @coachsession.reviews.each do |review| %>
          <div class="notification">
            <img src='https://kitt.lewagon.com/placeholder/users/arthur-littm' class="avatar-large" />
            <div class="notification-content">
              <p><small>14th January</small></p>
              <p id="review-<%= review.id %>"><%= review.content %></p>
            </div>
          </div>
        <% end %>
      <% end %>
    </div>
      <div>
      <%= simple_form_for([ @coachsession, @review ], url: coachsession_reviews_path(@coachsession), remote: true) do |f| %>
      <%= f.input :content, as: :text, label: "Share your experience" %>
      <button class="btn-booking">Review</button>
      <% end %>
      </div>
  </div>
  <div class="col-md-4 d-flex justify-content-end pe-0" >
    <div class="booking-card">
      <%= simple_form_for [@coachsession, @booking], url: coachsession_bookings_path(@coachsession) do |f| %>
        <%= f.input :date_start, as: :date, html5: true %>
        <%= f.input :date_end, as: :date, html5: true %>
        <p>Price per day:  $<%= @coachsession.price_per_day %></p>
        <%= f.button :submit, 'Book now', class:"btn-booking" %>
      <% end %>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>CoachWebapp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>

    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload', defer: true %>
  </head>

  <body>
    <% if devise_controller?  %>
    <% elsif  params[:controller] == "pages"%>
      <%= render 'shared/home-navbar' %>
    <% else %>
      <%= render 'shared/navbar' %>
    <% end %>

    <%= yield %>
  </body>
</html>

app/views/pages/home.html.erb
<div class="banner">
  <div class="container">
    <h1>Find your <strong>coach</strong>.</h1>
    <%# <%= simple_form_for :search, url: coachsessions_path, method: :get do |f| %>
      <%# <div class="search-form-control form-group">
        <label for="activities">Choose an activity:</label>
        <select id="activity" name="activities">
          <option value="Calisthenics">Calisthenics</option>
          <option value="Dancing">Dancing</option>
          <option value="Surfing">Surfing</option>
          <option value="Swimming">Swimming</option>
          <option value="Weightlifting">Weightlifting</option>
          <option value="Yoga">Yoga</option>
        </select>
        <button class="btn-flat" type="submit">Submit</button> %>

    <div>
      <%= form_tag coachsessions_path, method: :get do %>
      <%= text_field_tag :query,
          params[:query],
          class: "form-control",
          placeholder: "Surfing, Swimming, Weight-Lifting,...",
          class:"searchbar-home"%>
      <%= submit_tag "Search", class: "btn btn-search-home" %>
      <% end %>
    </div>
</div>

app/views/shared/_home-navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <div class="container-fluid">
    <%= link_to "FindCoach", root_path, class: "navbar-brand" %>

    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto">
        <% if user_signed_in? %>
           <li class="nav-item">
            <%= link_to "Become a coach", new_coachsession_path, class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to "My bookings", bookings_path, class: "nav-link" %>
          </li>
          <li class="nav-item dropdown">
            <%= image_tag "rayhan.jpg", class: "avatar dropdown-toggle", id: "navbarDropdown", data: { bs_toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
            <div class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
              <%= link_to "Log out", destroy_user_session_path, class: "dropdown-item", method: :delete %>
              <%#= link_to "Log out", destroy_user_session_path, method: :delete, class: "dropdown-item" %>
            </div>
          </li>
        <% else %>
          <li class="nav-item">
            <%= link_to "Login", new_user_session_path, class: "nav-link" %>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</div>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <div class="container-fluid">
    <%= link_to "FindCoach", root_path, class: "navbar-brand" %>

    <div class="searchbar">
       <%# <%= simple_form_for :search, url: coachsessions_path, method: :get do |f| %>
      <%# <div>
        <label for="activities">My activity:</label>
        <select id="activity" name="activities" placeholder="Choose your activity" class="dropdown">
          <option value="Calisthenics">Calisthenics</option>
          <option value="Dancing">Dancing</option>
          <option value="Surfing">Surfing</option>
          <option value="Swimming">Swimming</option>
          <option value="Weight-lifting">Weightlifting</option>
          <option value="Yoga">Yoga</option>
        </select>
        <button type="submit", class="btn-searchbar">Find</button>
        <% end %>
      <%# </div> %>
      <%= form_tag coachsessions_path, method: :get do %>
      <%= text_field_tag :query,
          params[:query],
          class: "form-control",
          placeholder: "Surfing, Swimming, Weight-Lifting,...",
          class:"searchbar-all"%>
      <%= submit_tag "Search", class: "btn btn-search-all" %>
      <% end %>
    </div>

    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto">
        <% if user_signed_in? %>
          <li class="nav-item">
            <%= link_to "Become a coach", new_coachsession_path, class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to "My bookings", bookings_path, class: "nav-link" %>
          </li>
          <li class="nav-item dropdown">
            <%= image_tag "rayhan.jpg", class: "avatar dropdown-toggle", id: "navbarDropdown", data: { bs_toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
            <div class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
              <%= link_to "Log out", destroy_user_session_path, class: "dropdown-item", method: :delete %>
              <%#= link_to "Log out", destroy_user_session_path, method: :delete, class: "dropdown-item" %>
            </div>
          </li>
        <% else %>
          <li class="nav-item">
            <%= link_to "Login", new_user_session_path, class: "nav-link" %>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</div>